### ISSUE TITLE
Compilation errors after updating kebs-spray-json to 1.8.1 (was 1.8.0)

### ISSUE THREAD

**Issue by plokhotnyuk** [theiterators/kebs#78]
They were detected by CI builds. Below are links to their stack traces when compiling for JS and JVM platforms accordingly: 

JS: https://github.com/plokhotnyuk/jsoniter-scala/pull/583/checks?check_run_id=1227740075#step:7:826

JVM: https://github.com/plokhotnyuk/jsoniter-scala/pull/583/checks?check_run_id=1227740098#step:7:2743
